-- Copyright The OpenTelemetry Authors
-- SPDX-License-Identifier: Apache-2.0

CREATE USER otelu WITH PASSWORD 'otelp';

-- Accounting Service: create a schema
CREATE SCHEMA accounting;
GRANT USAGE ON SCHEMA accounting TO otelu;

-- Accounting Service: create tables
CREATE TABLE accounting."order" (
    order_id TEXT PRIMARY KEY
);

CREATE TABLE accounting.shipping (
    shipping_tracking_id TEXT PRIMARY KEY,
    shipping_cost_currency_code TEXT NOT NULL,
    shipping_cost_units BIGINT NOT NULL,
    shipping_cost_nanos INT NOT NULL,
    street_address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    zip_code TEXT,
    order_id TEXT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES accounting."order"(order_id) ON DELETE CASCADE
);

CREATE TABLE accounting.orderitem (
    item_cost_currency_code TEXT NOT NULL,
    item_cost_units BIGINT NOT NULL,
    item_cost_nanos INT NOT NULL,
    product_id TEXT NOT NULL,
    quantity INT NOT NULL,
    order_id TEXT NOT NULL,
    PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES accounting."order"(order_id) ON DELETE CASCADE
);

-- Accounting Service: grant permission to schema
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA accounting TO otelu;

-- Product Review Service: create a schema
CREATE SCHEMA reviews;
GRANT USAGE ON SCHEMA reviews TO otelu;

-- Product Review Service: create tables
CREATE TABLE reviews.productreviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(16) NOT NULL,
    username VARCHAR(64) NOT NULL,
    description VARCHAR(1024),
    score NUMERIC(2,1) NOT NULL
);

-- Product Review Service: create index for product_id lookups
CREATE INDEX product_id_index ON reviews.productreviews (product_id);

-- Product Review Service: grant permission to schema
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA reviews TO otelu;

-- Product Review Service:  add product review data
INSERT INTO reviews.productreviews (product_id, username, description, score)
VALUES
    ('OLJCESPC7Z', 'party_planner_sue', 'Bought these for my kid''s birthday party and they held up great. No broken forks! For the price, you really can''t beat it.', '4.5'),
    ('OLJCESPC7Z', 'lazy_dishwasher', 'I''m not proud, but I use these daily. No dishes to wash. My therapist says it''s a phase. Five stars for enabling my lifestyle.', '5.0'),
    ('OLJCESPC7Z', 'office_lunch_hero', 'Keep a pack in my desk drawer at work. Saved the day when the office kitchen ran out of silverware. Coworkers think I''m a genius.', '4.0'),
    ('OLJCESPC7Z', 'picnic_pro', 'Perfect for outdoor picnics. Sturdy enough for potato salad, which is my only real benchmark for utensil quality.', '3.5'),
    ('OLJCESPC7Z', 'budget_betty', 'You get what you pay for, and at this price, you get a LOT of utensils. Some of the knives are a bit flimsy but the forks are solid.', '3.0'),

    ('66VCHSJNUP', 'tech_bargain', 'This cable charges my phone just as fast as the $30 brand name one. Braided cord feels premium. Best $5 I''ve spent this month.', '5.0'),
    ('66VCHSJNUP', 'cord_hoarder', 'I buy these in bulk and stash them everywhere — car, office, nightstand, backpack. They just work. No complaints.', '4.5'),
    ('66VCHSJNUP', 'skeptical_buyer', 'Was hesitant about an off-brand charger, but it''s been going strong for 3 months. The 6ft length is perfect for charging from the couch.', '4.0'),
    ('66VCHSJNUP', 'gadget_guy', 'Works great with my phone and tablet. Fast charging supported. The nylon braid hasn''t frayed at all. Genuinely impressed.', '5.0'),
    ('66VCHSJNUP', 'phone_addict', 'Charges fast, doesn''t overheat, and the length is just right. My cat hasn''t chewed through it yet either, which is a huge plus.', '4.5'),

    ('1YMWWN1N4O', 'spill_magnet', 'With two kids and a dog, I go through paper towels like water. This 8-pack lasts about a week. Great absorbency for the price.', '4.5'),
    ('1YMWWN1N4O', 'clean_freak_carl', 'These are solid 2-ply towels. Not quite Bounty, but honestly close enough. My countertops don''t know the difference.', '4.0'),
    ('1YMWWN1N4O', 'bulk_buyer', 'Love buying in bulk. These paper towels are absorbent, don''t fall apart when wet, and the rolls are full-sized. No cheating on sheet count.', '5.0'),
    ('1YMWWN1N4O', 'garage_mechanic', 'I use these for everything in my workshop — oil spills, cleaning parts, wiping hands. Tough enough for garage work at a fraction of the cost.', '4.5'),
    ('1YMWWN1N4O', 'kitchen_queen', 'Perfectly adequate paper towels. They do the job without breaking the bank. I''ve been buying these for months now and won''t switch back.', '4.0'),

    ('L9ECAV7KIM', 'night_jogger', 'Tiny but mighty! This little flashlight lights up my entire running path. The strobe mode is great for visibility. Batteries last a long time.', '5.0'),
    ('L9ECAV7KIM', 'camping_kevin', 'Threw this in my camping bag and it became the MVP of the trip. Bright enough to read by, small enough to clip to my tent.', '4.5'),
    ('L9ECAV7KIM', 'power_outage_pro', 'Bought 4 of these after a blackout. Now there''s one in every room. The three brightness modes are actually useful. Great emergency flashlight.', '4.5'),
    ('L9ECAV7KIM', 'dog_walker_dan', 'Perfect for evening dog walks. The aluminum body feels solid and the pocket clip is handy. Way brighter than I expected for the price.', '4.0'),
    ('L9ECAV7KIM', 'edc_enthusiast', 'Added this to my everyday carry. Impressively bright for its size. The strobe mode would definitely disorient someone. Not that I''ve tested that.', '5.0'),

    ('2ZYFJ3GM2N', 'neat_freak_nancy', 'These microfiber cloths are amazing. I use them on everything — mirrors, glasses, laptop screen. Zero streaks every time. Will buy again.', '5.0'),
    ('2ZYFJ3GM2N', 'car_detailer', 'Perfect for detailing my car. They pick up dust like magnets and don''t scratch paint. The color variety helps me keep track of which is for what.', '4.5'),
    ('2ZYFJ3GM2N', 'glasses_wearer', 'Finally, a cloth that actually cleans my glasses without smearing. I keep one at my desk and one in my bag. Total game changer.', '4.5'),
    ('2ZYFJ3GM2N', 'eco_warrior', 'Love that these are reusable. I''ve washed mine dozens of times and they still work great. Way better than disposable wipes for the environment.', '4.0'),
    ('2ZYFJ3GM2N', 'screen_cleaner', 'Use these for all my screens — TV, phone, tablet, monitors. They clean perfectly without any spray needed. Great value for a 12-pack.', '4.5'),

    ('0PUK6V6EV0', 'forgetful_chef', 'I burned three dinners before buying this timer. Zero burned dinners since. The loud beep could wake the dead, which is exactly what I need.', '5.0'),
    ('0PUK6V6EV0', 'tea_lover', 'Perfect for timing my tea steeps. The magnetic back sticks right to my fridge. Simple, effective, and the large display is easy to read.', '4.5'),
    ('0PUK6V6EV0', 'study_buddy', 'I use this for Pomodoro study sessions. 25 minutes on, 5 off. Much better than using my phone timer because I don''t get distracted.', '4.0'),
    ('0PUK6V6EV0', 'meal_prep_master', 'Essential for meal prep Sundays. I have two of these running simultaneously for different dishes. Loud enough to hear from the other room.', '5.0'),
    ('0PUK6V6EV0', 'egg_perfectionist', 'Soft boiled eggs require precision. This timer delivers. 6 minutes and 30 seconds, every time. My eggs have never been better.', '4.5'),

    ('LS4PSXUNUM', 'bath_time_parent', 'My toddler loves these ducks! They float perfectly and the squeak is hilarious. No mold issues since there''s no hole in the bottom. Smart design.', '5.0'),
    ('LS4PSXUNUM', 'desk_decorator', 'These sit on my office desk and bring me joy every single day. My coworkers are jealous. Three ducks, three times the happiness.', '4.5'),
    ('LS4PSXUNUM', 'collector_duck', 'Added these to my rubber duck collection. Classic yellow, perfect size, excellent squeak. A must-have for any serious duck enthusiast.', '5.0'),
    ('LS4PSXUNUM', 'gift_giver', 'Bought these as a gag gift for a friend''s birthday. They were the hit of the party. Now everyone wants their own set. Ordering more.', '4.0'),
    ('LS4PSXUNUM', 'pool_party_host', 'Tossed these in the pool for decoration at a summer party. They looked adorable floating around. Kids and adults both loved them.', '4.5'),

    ('9SIQT8TOJO', 'diy_dave', 'This tape has saved me more times than I can count. Leaky pipe? Duct tape. Broken taillight? Duct tape. 60 yards goes a long way.', '5.0'),
    ('9SIQT8TOJO', 'craft_queen', 'I use duct tape for all sorts of craft projects. The silver color is classic and it tears cleanly by hand. Strong adhesive that actually holds.', '4.5'),
    ('9SIQT8TOJO', 'moving_day_mike', 'Used three rolls of this during my last move. Sealed boxes, fixed a broken dolly handle, even made a temporary hinge. Indispensable.', '5.0'),
    ('9SIQT8TOJO', 'quick_fix_queen', 'Every junk drawer needs a roll of duct tape. This one is high quality — strong adhesive, doesn''t leave too much residue, and tears easily.', '4.0'),
    ('9SIQT8TOJO', 'survival_steve', 'Part of my emergency kit. Duct tape can fix almost anything in a pinch. This roll is a solid size and the adhesive is seriously strong.', '4.5'),

    ('6E92ZMYYFZ', 'remote_warrior', 'Stocked up and haven''t had to panic-search for batteries in months. Great shelf life and they last as long as the expensive brands.', '5.0'),
    ('6E92ZMYYFZ', 'parent_of_three', 'Between toys, remotes, and game controllers, we go through batteries fast. This 24-pack is a lifesaver. Good power output and great price.', '4.5'),
    ('6E92ZMYYFZ', 'flashlight_fan', 'I pair these with the LED flashlights from this store. Great combo. The batteries last a surprisingly long time. No leaking issues.', '4.5'),
    ('6E92ZMYYFZ', 'holiday_prepper', 'Bought these before Christmas for all the toys. Smart move — was the only parent not scrambling on Christmas morning. 10-year shelf life is clutch.', '5.0'),
    ('6E92ZMYYFZ', 'clock_collector', 'I have a lot of wall clocks. Don''t ask why. These batteries keep them all ticking reliably. Consistent quality across the entire pack.', '4.5'),

    ('HQTGWGPNH4', 'thrill_seeker', 'Got a pack of sticky notes, a phone charger, and rubber ducks. Honestly, best $10 I''ve ever spent. The mystery is half the fun.', '5.0'),
    ('HQTGWGPNH4', 'curious_cat', 'Ordered two bags and got completely different stuff in each. Love the surprise factor. It''s like a subscription box but way cheaper.', '4.5'),
    ('HQTGWGPNH4', 'gift_idea_genius', 'Bought these as stocking stuffers. Everyone loved the randomness. One bag had duct tape and a kitchen timer — practical AND fun.', '4.0'),
    ('HQTGWGPNH4', 'impulse_buyer', 'I didn''t need this. I don''t need most things I buy here. But the mystery called to me and I answered. No regrets. Contents were solid.', '4.5'),
    ('HQTGWGPNH4', 'value_hunter', 'The guaranteed $15+ value is legit. My bag had items that would have cost about $18 separately. Great deal if you like surprises.', '5.0');

-- Product Catalog Service: create a schema
CREATE SCHEMA catalog;
GRANT USAGE ON SCHEMA catalog TO otelu;

-- Product Catalog Service: create tables
CREATE TABLE catalog.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    picture TEXT,
    price_currency_code TEXT NOT NULL,
    price_units BIGINT NOT NULL,
    price_nanos INT NOT NULL,
    categories TEXT
);

-- Product Catalog Service: grant permission to schema
GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO otelu;

-- Product Catalog Service: add product data
INSERT INTO catalog.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories)
VALUES
    ('OLJCESPC7Z', '100-Pack Plastic Utensils', 'Assorted forks, knives, and spoons. Perfect for parties, picnics, or just giving up on dishes. Durable enough for a single use, cheap enough to not care. Includes 34 forks, 33 knives, and 33 spoons in classic white.', 'PlasticUtensils.jpeg', 'USD', 3, 990000000, 'kitchen,party'),
    ('66VCHSJNUP', 'Off-Brand Phone Charger', '6ft USB-C cable. Works surprisingly well for something that costs less than a coffee. Braided nylon exterior resists tangling and adds a touch of class to your bargain purchase. Compatible with most modern devices.', 'PhoneCharger.jpeg', 'USD', 4, 990000000, 'electronics,charging'),
    ('1YMWWN1N4O', 'Bulk Paper Towels (8-Pack)', 'The quicker picker-upper''s budget cousin. Gets the job done. Eight full-size rolls of 2-ply absorbent paper towels. Each roll has 80 sheets of spill-fighting power. Stock your kitchen, bathroom, and garage.', 'BulkPaperTowels.jpeg', 'USD', 7, 990000000, 'household,cleaning'),
    ('L9ECAV7KIM', 'LED Flashlight', 'Pocket-sized aluminum flashlight. 3 modes: bright, brighter, and strobe for emergencies or dance parties. Runs on 3 AAA batteries (not included, but we sell those too). Water-resistant and surprisingly blinding for its size.', 'LEDFlashlight.jpeg', 'USD', 5, 490000000, 'tools,lighting'),
    ('2ZYFJ3GM2N', 'Microfiber Cleaning Cloths (12-Pack)', 'Lint-free, streak-free, guilt-free. Clean everything from screens to countertops. These ultra-soft microfiber cloths are machine washable and reusable hundreds of times. Assorted colors so you can color-code your cleaning.', 'MicrofiberClothes.jpeg', 'USD', 6, 990000000, 'household,cleaning'),
    ('0PUK6V6EV0', 'Kitchen Timer (Digital)', 'Loud beep ensures you never forget about your leftovers in the microwave again. Large LCD display, magnetic back for fridge mounting, and a countdown range of up to 99 minutes and 59 seconds. Runs on one AAA battery.', 'kitchenTimer.jpeg', 'USD', 3, 490000000, 'kitchen,gadgets'),
    ('LS4PSXUNUM', 'Rubber Ducks (3-Pack)', 'Three classic yellow rubber ducks. Bathtime essential or desk decoration — we don''t judge. Each duck measures approximately 2 inches tall and floats upright. Squeaks when squeezed. BPA-free and safe for all ages.', 'RubberDucks.jpeg', 'USD', 2, 990000000, 'toys,bath'),
    ('9SIQT8TOJO', 'Duct Tape Roll (Silver)', '60 yards of the handyman''s secret weapon. Fixes everything except your life choices. Industrial-strength adhesive on a polyethylene-coated cloth backing. Tears easily by hand. The most versatile tool in any drawer.', 'ductTape.jpeg', 'USD', 4, 490000000, 'tools,hardware'),
    ('6E92ZMYYFZ', 'AA Batteries (24-Pack)', 'Because the remote always dies at the worst moment. Stock up. 24 long-lasting alkaline AA batteries with a 10-year shelf life. Powers everything from TV remotes to kids'' toys to that flashlight you keep meaning to find.', 'AABatteries.jpeg', 'USD', 8, 990000000, 'electronics,batteries'),
    ('HQTGWGPNH4', 'Mystery Grab Bag', 'A surprise assortment of WillfulWaste favorites. Could be anything. That''s the thrill. Each bag contains 3-5 items from our catalog, hand-picked by our warehouse team (or whoever is closest to the shelf). Guaranteed value over $15.', 'MysteryGrabBag.jpeg', 'USD', 9, 990000000, 'mystery,value');
