apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/npcomplete777/opentelemetry-demo.git
    targetRevision: main
    path: k8s/overlays/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: operator.dash0.com
      kind: Dash0Monitoring
      jsonPointers:
        - /spec/eventCollection
        - /spec/instrumentWorkloads/labelSelector
        - /spec/instrumentWorkloads/traceContext
        - /spec/synchronizePersesDashboards
        - /spec/synchronizePrometheusRules
