apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dash0-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: dash0-operator-injector
      jsonPointers:
        - /webhooks/0/objectSelector
  project: default
  source:
    repoURL: https://dash0hq.github.io/dash0-operator
    chart: dash0-operator
    targetRevision: 0.100.0
    helm:
      valuesObject:
        operator:
          dash0Export:
            enabled: true
            endpoint: ingress.us-west-2.aws.dash0.com:4317
            apiEndpoint: https://api.us-west-2.aws.dash0.com
            dataset: astronomy-demo
            disableSecretValidation: true
            secretRef:
              name: dash0-authorization-secret
              key: token
          collectors:
            daemonSetProbes:
              startup:
                initialDelaySeconds: 0
                periodSeconds: 2
                timeoutSeconds: 3
                failureThreshold: 120
  destination:
    server: https://kubernetes.default.svc
    namespace: dash0-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
