apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-agent
  namespace: otel-demo
spec:
  template:
    spec:
      containers:
        - name: opentelemetry-collector
          env:
            - name: CX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: coralogix-otel-secret
                  key: CX_API_KEY
