apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-agent
  namespace: otel-demo
data:
  relay: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 5s
        send_batch_size: 1000
      resource:
        attributes:
          - key: dash0.dataset
            value: default
            action: upsert
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: K8S_NODE_NAME
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.replicaset.name
            - k8s.daemonset.name
            - k8s.statefulset.name
            - k8s.job.name
            - k8s.node.name
            - k8s.container.name
            - container.id
            - container.image.name
            - container.image.tag
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection

    exporters:
      otlphttp/dash0:
        endpoint: https://ingress.us-west-2.aws.dash0.com
        headers:
          Authorization: "Bearer auth_weI4rzoX0bfwy2eKvpjtBTZAhQAcw11j"
      clickhouse:
        endpoint: tcp://k3d-clickhouse-server-0:30900
        database: otel
        ttl: 72h
        create_schema: false
        traces_table_name: otel_traces_v2
        logs_table_name: otel_logs
        metrics_table_name: otel_metrics
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
        sending_queue:
          enabled: true
          num_consumers: 4
          queue_size: 1000
        timeout: 15s
      elasticsearch:
        endpoints:
          - http://k3d-elasticsearch-server-0:30920
        logs_index: otel-logs
        traces_index: otel-traces
        sending_queue:
          enabled: true
          num_consumers: 4
          queue_size: 1000
        retry:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
        flush:
          bytes: 5000000
      debug:
        verbosity: basic

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes, batch, resource]
          exporters: [otlphttp/dash0, clickhouse, elasticsearch, debug]
        metrics:
          receivers: [otlp]
          processors: [k8sattributes, batch, resource]
          exporters: [otlphttp/dash0, clickhouse, debug]
        logs:
          receivers: [otlp]
          processors: [k8sattributes, batch, resource]
          exporters: [otlphttp/dash0, clickhouse, elasticsearch, debug]
