apiVersion: v1
kind: Service
metadata:
  name: flagd-ui-nodeport
  namespace: otel-demo
spec:
  type: NodePort
  ports:
    - name: http-ui
      port: 4000
      targetPort: 4000
      nodePort: 30400
  selector:
    opentelemetry.io/name: flagd
