apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-proxy
spec:
  template:
    spec:
      containers:
        - name: frontend-proxy
          image: ghcr.io/npcomplete777/opentelemetry-demo/frontend-proxy:latest
          env:
            - name: DASH0_WEB_PROXY_HOST
              value: dash0-web-proxy
            - name: DASH0_WEB_PROXY_PORT
              value: "8090"
