apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: otel-demo
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth]
    disable_login_form = true
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Admin
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = 192.168.97.3
    root_url = http://192.168.97.3:30380/grafana
    serve_from_sub_path = true
    [unified_storage]
    index_path = /var/lib/grafana-search/bleve
