apiVersion: v1
kind: Service
metadata:
  name: jaeger-nodeport
  namespace: otel-demo
spec:
  type: NodePort
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
      nodePort: 30686
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/component: all-in-one
